version: '3.7'
services:
  postgres:
    image: ghcr.io/deltasystems/docker-development-environments/lapp-8-postgres:latest
    ports:
      - "5433:5432"
    #volumes:
      #- "./postgres-on-init:/docker-entrypoint-initdb.d"
  memcached:
    image: ghcr.io/deltasystems/docker-development-environments/lapp-8-memcached:latest
    ports:
      - "11211:11211"
  web:
    image: ghcr.io/deltasystems/docker-development-environments/lapp-8-web:latest
    ports:
      - "8081:80"
    volumes:
      #- "./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      #- "./conf/supervisor:/etc/supervisor/conf.d"
      - "./conf/cron/crontab.txt:/etc/cron.d/crontab"
      - "./src:/var/www/vhosts/myvhost"
      #- "./conf/gelf/gelf.key:/root/.ssh/gelf.key.mounted"
      #- "./deploy.php:/var/www/vhosts/myvhost/private/deploy.php"
    links:
      - 'postgres:postgres'
      - 'memcached:memcached'